# version: "3.9"

# services:
#   app:
#     image: todo-app:v1.0.2   # Image มี Nginx + Next.js ในตัวแล้ว
#     container_name: nextjs-app
#     ports:
#       - "80:80"              # Nginx port (ไม่ใช่ 3000 แล้ว)
#       # - "443:443"          # Uncomment for SSL
#     environment:
#       # เลือก DB runtime
#       DB_TYPE: mongo    # เปลี่ยนเป็น postgres / mariadb / mongo ได้ตามต้องการ

#       # MariaDB
#       MARIADB_HOST: mariadb
#       MARIADB_USER: todo
#       MARIADB_PASSWORD: secret
#       MARIADB_DATABASE: todo_app
#       MARIADB_PORT: 3306

#       # Postgres
#       POSTGRES_HOST: postgres
#       POSTGRES_USER: todo
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DATABASE: todo_app
#       POSTGRES_PORT: 5432

#       # MongoDB
#       MONGO_HOST: mongo
#       MONGO_USER: todo
#       MONGO_PASSWORD: secret
#       MONGO_DATABASE: todo_app
#       MONGO_PORT: 27017

#       NODE_ENV: production
#     restart: unless-stopped
#     networks:
#       - todo-net
#     # depends_on:
#     #   - mariadb
#     #   - postgres
#     #   - mongo

# networks:
#   todo-net:
#     external: true   # ต้องมี network ของ DB สร้างไว้ก่อน
version: "3.9"

services:
  # =========================
  # app1 : MariaDB
  # =========================
  app1:
    image: todo-app:v1.0.0-mariadb
    container_name: app1
    ports:
      - "3001:3000"
    environment:
      DB_TYPE: mariadb
      NEXT_PUBLIC_BASE_PATH: /app1

      MARIADB_HOST: mariadb
      MARIADB_USER: todo
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: todo_app
      MARIADB_PORT: 3306

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

  # =========================
  # app2 : PostgreSQL
  # =========================
  app2:
    image: todo-app:v1.0.0-postgres
    container_name: app2
    ports:
      - "3002:3000"
    environment:
      DB_TYPE: postgres
      NEXT_PUBLIC_BASE_PATH: /app2

      POSTGRES_HOST: postgres
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: todo_app
      POSTGRES_PORT: 5432

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

  # =========================
  # app3 : MongoDB
  # =========================
  app3:
    image: todo-app:v1.0.0-mongodb
    container_name: app3
    ports:
      - "3003:3000"
    environment:
      DB_TYPE: mongo
      NEXT_PUBLIC_BASE_PATH: /app3

      MONGO_HOST: mongo
      MONGO_USER: todo
      MONGO_PASSWORD: secret
      MONGO_DATABASE: todo_app
      MONGO_PORT: 27017

      NODE_ENV: production
    restart: unless-stopped
    networks:
      - todo-net

networks:
  todo-net:
    external: true
